name: 编译 "apollolake-7.1.0-42661"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 同步仓库
        uses: actions/checkout@v2
      - name: 构建工具链
        run: 
          sudo chmod  777 *
          cd buildpat
          sudo ./buildpat-918p-7.1-42661.sh
     - name: 添加扩展驱动
        run: 
           sudo ./ext-manager.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json
#          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://github.com/jumkey/redpill-load/raw/develop/redpill-acpid/rpext-index.json
#          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://github.com/jumkey/redpill-load/raw/develop/redpill-virtio/rpext-index.json
#          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://github.com/jumkey/redpill-load/raw/develop/redpill-boot-wait/rpext-index.json
#          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://github.com/RedPill-TTG/redpill-boot-wait/raw/master/recipes/universal.json
#          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://github.com/RedPill-TTG/redpill-virtio/raw/master/recipes/ds918p_41890.json
#          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/r8169/rpext-index.json
      - name: 编译引导镜像
        run: sudo ./build-loader.sh DS918+ 7.1.0-42661
      - name: 上传镜像到 github actions
        uses: actions/upload-artifact@v2
        with:
          name: dsm-apollolake-7.1.0-42661
          path: images/redpill-DS[39]*.img
          if-no-files-found: error
